### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by viniciustelles** [ricardomachadosb/Spring-MVC-RESTful#1]
do you can create a readme.me. The project has things to do?
I have interest in contributing.

**Comment by ricardomachadosb** [comment]
Actually it's a project for a selective process that i am going through right now. So, it is not open yet for contribuitions Hahaha. But it will be open soon, i will create a readme when it's done and open for contribuitions. Tkx for your interest

**Comment by ricardomachadosb** [comment]
Added README.md file
